
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: WKSP_DGRPRETIUS  Date: Sun Jun 20 04:08:40 2021 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'planets',
      p_base_path      => '/planets/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'planets',
      p_pattern        => 'details',
      p_priority       => 0,
      p_etag_type      => 'NONE',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'planets',
      p_pattern        => 'details',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare
  v_response_json   clob;
  v_planets         varchar2(4000);
  v_planets_list    varchar2(4000);
  v_details         varchar2(4000);
  v_plantet_detail  varchar2(4000);

begin
  -- instert for your check
  insert into json (the_date, body)
       values (sysdate, :body)
    returning body into v_response_json;
  commit;  
  -- parse json
  apex_json.parse(v_response_json);

  -- get intresting parts
  v_planets     := apex_json.get_varchar2(''queryResult.parameters.planet'');  
  v_details     := apex_json.get_varchar2(''queryResult.parameters.detail''); 
  -- enitity planets 
  case when v_planets is not null then
  -- listagg all planets
  select 
    listagg(name, '', '') within group (order by id) name
  into
    v_planets_list
  from
    planets;

      :fulfillmentText := ''All planets in Solar System: '' || v_planets_list || ''. Any else?'';
  else 
      :fulfillmentText := ''No planets :( '';
  end case;
  -- entity details
  if v_details is not null then
  -- interesting fact about planet
    select
      details
    into 
      v_plantet_detail
    from planets where upper(name) = upper(v_details);

    :fulfillmentText := ''Interesting fact about planet: '' || v_details || '', is that: '' || v_plantet_detail  || ''. Any else? '';

  end if;

  exception
    WHEN no_data_found THEN
    :fulfillmenttext := ''no data'';
            when others then
                :fulfillmentText := ''Error from Database'';

end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'planets',
      p_pattern            => 'details',
      p_method             => 'POST',
      p_name               => 'fulfillmentText',
      p_bind_variable_name => 'fulfillmentText',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

        
COMMIT;

END;