-- create tables
create sequence planets_seq;

create table planets (
    id                             number default on null planets_seq.NEXTVAL 
                                   constraint planets_id_pk primary key,
    name                           varchar2(255 char),
    details                        varchar2(4000 char)
)
;

create sequence json_seq;

create table json (
    id                             number default on null json_seq.NEXTVAL 
                                   constraint json_id_pk primary key,
    the_date                       date,
    body                           clob
)
;


-- triggers
-- load data
 
insert into planets (
    id,
    name,
    details
) values (
    1,
    'Mercury',
    'Mercury is hot, but not too hot for ice'
);

insert into planets (
    id,
    name,
    details
) values (
    2,
    'Venus',
    'Venus doesn’t have any moons, and we aren’t sure why'
);

insert into planets (
    id,
    name,
    details
) values (
    3,
    'Earth',
    'You can see Earth’s magnetic field at work during light shows.'
);

insert into planets (
    id,
    name,
    details
) values (
    4,
    'Mars',
    'Mars had a thicker atmosphere in the past');

insert into planets (
    id,
    name,
    details
) values (
    5,
    'Jupiter',
    'Jupiter is a great comet catcher'
);

insert into planets (
    id,
    name,
    details
) values (
    6,
    'Saturn',
    'No one knows how old Saturn’s rings are'
);

insert into planets (
    id,
    name,
    details
) values (
    7,
    'Uranus',
    'Uranus is more stormy than we thought');

insert into planets (
    id,
    name,
    details
) values (
    8,
    'Neptune',
    'Neptune has supersonic winds'
);

commit;
-- load data
 
-- Generated by Quick SQL Sunday June 20, 2021  13:47:12
 
/*
planets /insert 8
    name
    details
json
    date
    body clob

# settings = { PK: "SEQ", semantics: "CHAR", language: "EN", APEX: true }
*/
